feat: Create the update script for 7.4 to 7.5
lamassu/lamassu-install pull request #50
Opened 2020-12-16 20:29 UTC by liordino

feat: update node to version 14

feat: update supervisor config

fix: removed check for version 7.5 install

fix: install curl prior to updating node

fix: make everything unattended

fix: update to ubuntu 20.04

fix: divided the script in two parts, one to upgrade ubuntu to 18.04 and
another do update it to 20.04 and do the all the rest

2020-12-24 16:02 UTC, chaotixkilla approved these changes

2021-01-05 15:32 UTC, naconner requested changes
This script needs to update operators currently on v7.5 to any future l-s versions, as it's currently meant to. Whereas these changes are only good for updating v7.4 operators once.

2021-01-05 15:32 UTC, naconner commented on upgrade
> +elif [[ "$UBUNTU_VERSION" == "20.04" ]]; then
This doesn't mean the system is up-to-date. This same script needs to accomodate operators who had installed v7.5.0 fresh for the first time, starting with 20.04, and who in the future need to go from v7.5.0 to v7.5.1, or whatever the latest version is.

2021-01-05 15:51 UTC, naconner requested changes
Need to instruct operators clearly.

2021-01-05 15:51 UTC, naconner commented on upgrade
> +  echo "Update part 1 complete! Reboot the server, make sure that Ubuntu is now on version 18.04 and run this script again to execute the second step."
Part 1 of how many? How does an operator reboot the server? How does one make sure it's on 18.04 (and doesn't the script check that for them)?

Also, use spacing:

```
echo
echo "Update part 1 of 2 complete!"
echo "You must now reboot this server, log in again, and run this script again to complete the upgrade."
echo "Paired machines will not be online until you do so."
echo "Reboot your server by running the following command:"
echo
echo "shutdown -r now"
echo
```

2021-01-05 15:51 UTC, naconner commented on upgrade
> +  echo "Detected Ubuntu version: 18.04. Executing upgrade script part 2 (you may need to reboot more than once to finish this step)..."
Reboot more than once? How do they know if and when to?

2021-01-05 15:51 UTC, naconner commented on upgrade
> +  echo "Update part 3 complete! Restart the server to complete the process."
Hadn't informed somewhere that we were going from part 2 to a part 3.

```
echo
echo "Update part 2 of 2 complete!"
echo "You must now reboot this server to finish the update."
echo "Paired machines will not be online until you do so."
echo "Reboot your server by running the following command:"
echo
echo "shutdown -r now"
echo
```

2021-02-11 10:33 UTC, closed without merging