feat: add wallet nodes update script to update-ls
lamassu/lamassu-install pull request #69
Opened 2021-10-09 22:37 UTC by josepfo

2021-10-28 21:27 UTC, chaotixkilla approved these changes

2021-11-14 23:11 UTC, RafaelTaranto requested changes

2021-11-14 23:11 UTC, RafaelTaranto commented on upgrade-ls
> +
I think this should happen before we show the message that the l-s update is complete, no?

2021-11-17 10:39 UTC, RafaelTaranto commented on upgrade-ls
> +
@josepfo not exactly what I mean, is just that we're updating the nodes even if the l-s update fails, this should be happening only after a successfull l-s update, hence the "before showing the L-S message"

2021-11-19 14:09 UTC, RafaelTaranto approved these changes

2021-11-19 14:10 UTC, merged